### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by ultimater-debug** [allandecastro/VATNumberValidator#11]
Somehow it doesn't work no more :/
Thx for this free vatvalidation

**Comment by TomDevolder** [comment]
Same here. Loading spinner doesn't stop. Anyone found a solution yet?

**Comment by allandecastro** [comment]
Hello all :)
I think this is due to the CORS proxy used, it was free but as many people were using it, the owner decided to stop the service. So we never receive any results from the API as the redirect service is closed.

You can find another CORS proxy or build an internal development (Custom API or Azure Function) and update the PCF according to your endpoint :)
