### ISSUE TITLE
Public demo server (cors-anywhere.herokuapp.com) will be very limited by January 2021, 31st

### ISSUE THREAD

**Issue by vseykov** [allandecastro/VATNumberValidator#2]
Hi, Great Tool!

However the website you are connecting to validate the service has been taken off for commercial use!
https://cors-anywhere.herokuapp.com/corsdemo

do you have any idea or plans to redirect it to a working proxy?

**Comment by allandecastro** [comment]
Hello vseykov,

Thanks a lot for your feedback!
I do not have a free workaround at this time, but you can easily create an Azure Function which will be called by the PCF and the azure function will perform the request against the webservice!

**Comment by bo-stig-christensen** [comment]
Hi @allandecastro ,
I had a look around and found this: https://nordicapis.com/10-free-to-use-cors-proxies/

Looking at this list, I think it might be viable to have a look at a couple of them:
https://cors-proxy.htmldriven.com/
https://github.com/Freeboard/thingproxy

It could be an idea to do a try-catch and if the first doesn't work, reroute to the second.
It would be a generic replacement for the current logic, provided that the documentation is up-to-date and the services work ;-)

I might have some time soon to look at this and possibly make a pull request, but for now I wanted to reactivate this issue and then we will see who gets time first to fix it ;-)

**Comment by bo-stig-christensen** [comment]
@vseykov : In case you cannot wait for @allandecastro to merge the Pull Request, you are welcome to steal a version 1.1 of the solution from my repo: https://github.com/bo-stig-christensen/VATNumberValidator/tree/master/Deployment ;-)

I have tested it in a D365 instance with success.... and since the change was rather simple, I simply assume it is working as before but now with a properly working CORS Proxy :-)
